// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Only provide datasource URL when available.
  // This prevents prisma generate from failing during Vercel builds
  // before a real DATABASE_URL has been added.
  datasource: process.env["DATABASE_URL"]
    ? { url: process.env["DATABASE_URL"] }
    : undefined,
});
